# 사이트 기본 정보
title: "Columnia"
email: me@xavierchoi.blog
description: >-
  A fast and easy markdown Jekyll blog theme with multilingual support.

# GitHub Pages 배포 설정
baseurl: "/columnia-blog"
url: "https://xavierchoi.github.io"

# 소셜 미디어
twitter_username: whereisxavier

# Build settings
markdown: kramdown
highlighter: rouge
safe: false

# Jekyll 플러그인
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate-v2
  - jekyll-admin

# Jekyll Admin 설정
jekyll_admin:
  # 파일 업로드 허용
  uploads_dir: assets/images
  # 업로드 가능한 파일 확장자
  uploads_ext_whitelist:
    - jpg
    - jpeg
    - png
    - gif
    - webp
    - svg
    - ico

# Static files 처리 설정
include:
  - "assets/images"

# 기본 레이아웃 설정
defaults:
  - scope:
      path: "assets/images"
    values:
      image: true
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
  - scope:
      path: ""
    values:
      layout: "default"

# 시간 및 지역 설정
future: true
timezone: Asia/Seoul

# 퍼포먼스 설정
incremental: false
show_drafts: false

# Sass/SCSS 설정
sass:
  sass_dir: _sass
  style: compressed

# SEO 및 소셜 미디어 설정
twitter:
  username: whereisxavier
  card: summary_large_image

# jekyll-paginate-v2 설정 (커스텀 플러그인과 호환)
pagination:
  enabled: true
  per_page: 10
  permalink: '/page/:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

# 빌드에서 제외할 파일들
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - "*.gem"
  - "*.gemspec"
  - tools/
  - README.md
  - CHANGELOG.md
  - LICENSE
  - Rakefile
  - .github/